In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
DATA_PATH = "../data/processed/audio_features.csv"

df = pd.read_csv(DATA_PATH)

df.head()

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,file_name
0,-726.21720,68.54142,3.293398,12.205300,5.510278,13.667410,-2.983828,3.098029,-3.310813,-1.564384,...,1.538184e-09,-4.999099e-09,3.076369e-09,-4.614553e-09,6.152737e-09,-1.538184e-09,3.460915e-09,1.922730e-09,-1.922730e-09,03-01-01-01-01-01-01.wav
1,-719.12830,70.20157,1.168397,13.122541,7.836950,14.411290,-4.111360,4.468973,-3.539367,-3.658608,...,3.046883e-09,6.093766e-09,4.570324e-09,1.523441e-09,-3.046883e-09,5.332045e-09,-3.046883e-09,5.332045e-09,-1.142581e-09,03-01-01-01-01-02-01.wav
2,-714.99570,69.68935,3.924564,11.924190,6.421723,11.011614,-2.878103,4.509558,-4.476109,-2.671549,...,-1.416488e-02,-1.359491e-02,-1.295078e-02,-1.223024e-02,-1.143390e-02,-1.057602e-02,-9.686350e-03,-8.801757e-03,-7.952768e-03,03-01-01-01-02-01-01.wav
3,-710.97530,67.56488,5.782240,13.230727,6.190846,12.628252,-1.675169,5.657494,-4.950634,-3.477545,...,-1.245889e-02,-1.138254e-02,-1.104492e-02,-1.258594e-02,-1.402821e-02,-1.450868e-02,-1.359997e-02,-1.002229e-02,-5.964142e-03,03-01-01-01-02-02-01.wav
4,-759.92175,75.78352,6.023605,14.557394,6.454188,14.631508,-3.004551,4.620970,-5.200016,-0.707430,...,-2.241025e-02,-2.091691e-02,-1.987888e-02,-1.897472e-02,-1.749858e-02,-1.506914e-02,-1.225449e-02,-9.423181e-03,-7.121702e-03,03-01-02-01-01-01-01.wav

In [3]:
file_names = df["file_name"]

X = df.drop(columns=["file_name"])

print("Feature Shape:", X.shape)

Feature Shape: (1440, 39)

In [4]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [5]:
X_scaled_df = pd.DataFrame(
    X_scaled,
    columns=X.columns
)

X_scaled_df["file_name"] = file_names

X_scaled_df.head()

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,file_name
0,-1.063756,0.165255,0.691232,0.246091,0.834620,0.754703,0.890069,0.424851,0.780238,0.928137,...,-0.024551,0.035300,0.032998,0.030189,0.017152,0.025025,0.041286,0.090386,0.122804,03-01-01-01-01-01-01.wav
1,-0.994626,0.277280,0.510977,0.358848,1.173437,0.858311,0.704162,0.687790,0.734243,0.446494,...,-0.024551,0.035301,0.032998,0.030190,0.017150,0.025026,0.041285,0.090387,0.122805,03-01-01-01-01-02-01.wav
2,-0.954325,0.242716,0.744771,0.211534,0.967347,0.384805,0.907501,0.695574,0.545731,0.673504,...,-1.903202,-1.793683,-1.830874,-1.792491,-1.642013,-1.670757,-1.592613,-1.465834,-1.391754,03-01-01-01-02-01-01.wav
3,-0.915118,0.099359,0.902350,0.372147,0.933726,0.609970,1.105841,0.915741,0.450237,0.488136,...,-1.676941,-1.496043,-1.556583,-1.845502,-2.018470,-2.301329,-2.252764,-1.681633,-1.013032,03-01-01-01-02-02-01.wav
4,-1.392440,0.653942,0.922824,0.535235,0.972075,0.888982,0.886653,0.716942,0.400051,1.125225,...,-2.996762,-2.778744,-2.827963,-2.797626,-2.522053,-2.391194,-2.025809,-1.575707,-1.233482,03-01-02-01-01-01-01.wav

In [6]:
X_scaled_df = pd.DataFrame(
    X_scaled,
    columns=X.columns
)

X_scaled_df["file_name"] = file_names

X_scaled_df.head()

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,file_name
0,-1.063756,0.165255,0.691232,0.246091,0.834620,0.754703,0.890069,0.424851,0.780238,0.928137,...,-0.024551,0.035300,0.032998,0.030189,0.017152,0.025025,0.041286,0.090386,0.122804,03-01-01-01-01-01-01.wav
1,-0.994626,0.277280,0.510977,0.358848,1.173437,0.858311,0.704162,0.687790,0.734243,0.446494,...,-0.024551,0.035301,0.032998,0.030190,0.017150,0.025026,0.041285,0.090387,0.122805,03-01-01-01-01-02-01.wav
2,-0.954325,0.242716,0.744771,0.211534,0.967347,0.384805,0.907501,0.695574,0.545731,0.673504,...,-1.903202,-1.793683,-1.830874,-1.792491,-1.642013,-1.670757,-1.592613,-1.465834,-1.391754,03-01-01-01-02-01-01.wav
3,-0.915118,0.099359,0.902350,0.372147,0.933726,0.609970,1.105841,0.915741,0.450237,0.488136,...,-1.676941,-1.496043,-1.556583,-1.845502,-2.018470,-2.301329,-2.252764,-1.681633,-1.013032,03-01-01-01-02-02-01.wav
4,-1.392440,0.653942,0.922824,0.535235,0.972075,0.888982,0.886653,0.716942,0.400051,1.125225,...,-2.996762,-2.778744,-2.827963,-2.797626,-2.522053,-2.391194,-2.025809,-1.575707,-1.233482,03-01-02-01-01-01-01.wav

In [7]:
OUTPUT_PATH = "../data/processed/normalized_features.csv"

X_scaled_df.to_csv(OUTPUT_PATH, index=False)

print("Normalized features saved successfully!")

Normalized features saved successfully!

## Feature Normalization

Feature normalization is an important preprocessing step in machine learning.

The extracted MFCC, Delta, and Delta-Delta features may have different numerical ranges. If clustering algorithms are applied directly to such data, features with larger values can dominate the distance calculations.

To avoid this issue, we apply **StandardScaler**, which standardizes features using:

z = (x − μ) / σ

where:

μ = mean of the feature  
σ = standard deviation of the feature

After normalization:

• Each feature has mean ≈ 0  
• Each feature has standard deviation ≈ 1  

This ensures that all features contribute equally during clustering.